set nocompatible

if has('nvim')
  set runtimepath^=~/.vim
  set runtimepath+=~/.vim/after
endif

let s:dotfiles_dir = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')
let s:vimrc_dir = s:dotfiles_dir.'/vim'

set backspace=eol,start,indent
set cursorline
set display=lastline
set hidden
set laststatus=2
set list
set listchars=tab:\|\ ,trail:.,extends:>,precedes:<
set matchtime=2
set number
set showcmd
set showmatch
set showtabline=1
set splitbelow
set splitright
set wildmenu
set wildmode=full
set foldmethod=indent
set foldlevel=5

set ignorecase
set smartcase
set hlsearch
set incsearch

set shiftwidth=2
set tabstop=8
set softtabstop=2
set expandtab

filetype plugin indent on
syntax enable on

" Backup / Undo / Swap files
set backup
set writebackup
set swapfile
set undolevels=1024
if has('nvim')
  set backupdir=~/.config/nvim/tmp
  set backupext=.bak
  set undodir=~/.config/nvim/undo
  set undofile
  silent! call mkdir(expand('~/.config/nvim/tmp'), "p", 0755)
  silent! call mkdir(expand('~/.config/nvim/undo'), "p", 0755)
else
  set backupdir=~/.vim/tmp
  set backupext=.bak
  set undodir=~/.vim/undo
  set undofile
  silent! call mkdir(expand('~/.vim/tmp'), "p", 0755)
  silent! call mkdir(expand('~/.vim/undo'), "p", 0755)
endif

function! s:handle_large_file()
  let large_file_size = 20 * 1024 * 1024
  let file = expand('<afile>')
  if getfsize(file) > large_file_size
    setlocal nobackup
    setlocal noswapfile
  endif
endfunction
autocmd BufReadPre * call s:handle_large_file()

" Key mappings
let g:mapleader = "\<Space>"
inoremap jk <ESC>
nnoremap <leader>w <cmd>w<cr>
nnoremap `n <cmd>noh<cr>
inoremap {<cr> {<cr>}<esc>ko

" Don't use Ex mode, use Q for formatting
nnoremap Q gq

inoremap <c-a> <home>
inoremap <c-e> <end>
inoremap <c-d> <del>
inoremap <c-_> <c-k>
inoremap <c-f> <right>
inoremap <c-b> <left>
inoremap <m-b> <c-left>
inoremap <m-f> <c-right>

inoremap <c-h> <left>
inoremap <c-j> <down>
inoremap <c-k> <up>
inoremap <c-l> <right>

nnoremap <m-j> gj
nnoremap <m-k> gk
inoremap <m-j> <c-o>gj
inoremap <m-k> <c-o>gk

nnoremap <m-H> <c-w>h
nnoremap <m-L> <c-w>l
nnoremap <m-J> <c-w>j
nnoremap <m-K> <c-w>k

command! -bang W w
command! -bang Wq wq
command! -bang WQ wq
command! -bang Q q
command! -bang QA qa

" Restore cursor to file position in previous editing session
autocmd BufReadPost *
        \ if line("'\"") > 1 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif

" Automatically load .vimrc source when saved
autocmd! BufWritePost vimrc source $MYVIMRC

execute 'source '.fnameescape(s:vimrc_dir.'/plugin.vim')
try | colorscheme codedark | catch /.*/ | endtry
